/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId =
  import.meta.env.VITE_SUPABASE_PROJECT_ID ||
  "itpqebuaviouyybkbczn";

export const publicAnonKey =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0cHFlYnVhdmlvdXl5YmtiY3puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NTIyNjAsImV4cCI6MjA5MDQyODI2MH0.UqPnNrNR9t9hfaPgRR5kLGuYladBgmrSBN8SxX7arMg";