/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dcdbucqrvhzbbrxzqhij"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZGJ1Y3Fydmh6YmJyeHpxaGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDc5MjAsImV4cCI6MjA5MDYyMzkyMH0.xGnAE7QLensjv79GtoXVL1udp49P6VI9dUL3LsvWgWQ"
export const SERVER = "https://dcdbucqrvhzbbrxzqhij.supabase.co/functions/v1/server";
