import { createContext, useContext, useState, ReactNode } from "react";

export type Language = "en" | "ms" | "zh";

const translations = {
  en: {
    nav: {
      orders: "Orders",
      expenses: "Expenses",
      analytics: "Analytics",
      settings: "Settings",
      stock: "Stock",
    },
    common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      edit: "Edit",
      add: "Add",
      close: "Close",
      confirm: "Confirm",
      total: "Total",
      date: "Date",
      notes: "Notes",
      export: "Export",
      import: "Import",
      loading: "Loading...",
      saving: "Saving...",
      saved: "Saved",
      offline: "Offline",
      cloudSync: "Cloud sync",
      signOut: "Sign Out",
      actions: "Actions",
      quantity: "Quantity",
      unit: "Unit",
      or: "OR",
      remove: "Remove",
      businessSystem: "Business Management System",
      renewNow: "Renew Now",
    },
    orders: {
      title: "Order Summary",
      cart: "Cart",
      items: "items",
      emptyCart: "Cart is empty",
      placeOrder: "Place Order",
      subtotal: "Subtotal",
      discount: "Discount",
      discountType: "Discount Type",
      percentage: "Percentage (%)",
      fixedAmount: "Fixed Amount (RM)",
      discountPercentage: "Discount Percentage",
      discountAmount: "Discount Amount",
      addToCart: "Add to Cart",
      receipt: "Receipt",
      printReceipt: "Print Receipt",
      officialReceipt: "OFFICIAL RECEIPT",
      receiptNo: "Receipt No",
      itemsLabel: "ITEMS",
      thankYou: "Thank you for your business!",
      comeAgain: "Please come again",
      pricePerUnit: "Price:",
      totalLabel: "Total:",
      subtotalLabel: "Subtotal:",
      totalFinal: "TOTAL:",
      discountFixed: "(Fixed)",
      cashReceived: "Cash Received",
      change: "Change",
      payment: "Payment",
      time: "Time",
      paymentCash: "Cash",
      paymentQr: "QR",
      paymentCard: "Card",
    },
    expenses: {
      title: "Expense Management",
      description: "Track costs and materials for your products",
      totalExpenses: "Total Expenses",
      productManagement: "Product Management",
      productManagementDesc: "Click a product card to log an expense. Use the toggle to show or hide a product in the Orders section.",
      recentExpenses: "Recent Expenses",
      noExpenses: "No expenses recorded yet",
      addExpense: "Add Expense",
      addExpenseDesc: "Record the cost of materials or products",
      addProduct: "Add Product",
      addProductTitle: "Add New Product",
      addProductDesc: "Create a new product to track expenses",
      editProduct: "Edit Product",
      editProductDesc: "Update product details",
      deleteProduct: "Delete Product",
      deleteProductConfirm: "Are you sure you want to delete this product? This action cannot be undone.",
      updateProduct: "Update Product",
      productName: "Product Name",
      productNamePlaceholder: "e.g., Boba Tea, Coffee Beans",
      category: "Category",
      categoryPlaceholder: "e.g., Beverages, Ingredients",
      costPerUnit: "Cost per Unit (RM)",
      sellingPrice: "Selling Price (RM)",
      unitType: "Unit Type",
      initialStock: "Initial Stock",
      stock: "Stock",
      productImage: "Product Image",
      uploadImage: "Upload Image",
      pasteImageUrl: "Paste image URL here",
      showInOrders: "Show in Orders section",
      showInOrdersDesc: "Uncheck if this is a raw material / ingredient not sold directly",
      inOrders: "✓ In Orders",
      hidden: "✕ Hidden",
      hideFromOrders: "Hide from Orders",
      showInOrdersBtn: "Show in Orders",
      totalCost: "Total Cost",
      costPerUnitCol: "Cost/Unit",
      product: "Product",
    },
    analytics: {
      title: "Profit Analytics",
      totalRevenue: "Total Revenue",
      totalCost: "Total Cost",
      netProfit: "Net Profit",
      profitMargin: "Profit Margin",
      orders: "Orders",
      voidOrder: "Void Order",
      voidOrderConfirm: "Are you sure you want to void this order? This cannot be undone.",
      transactionHistory: "Transaction History",
      transactionDesc: "All completed sales — sorted latest first",
      topProducts: "Top Selling Products",
      topProductsDesc: "Best performing products by revenue",
      salesReport: "Sales Report",
      showingFor: "Showing summary for:",
      todaySales: "Today's Sales",
      ordersToday: "orders today",
      totalSales: "Total Sales",
      completedOrders: "completed orders",
      totalExpenses: "Total Expenses",
      expenseEntries: "expense entries",
      margin: "margin",
      monthlyPerformance: "Monthly Performance",
      monthlyDesc: "Sales, expenses, and profit breakdown",
      noTransactions: "No transactions for selected period",
      noExpenses: "No expenses for selected period",
      noSalesData: "No sales data for selected period",
      dateTime: "Date & Time",
      orderId: "Order ID",
      items: "Items",
      amount: "Amount",
      showAll: "Show All",
      showLess: "Show Less",
      showing: "Showing",
      of: "of",
      expenseHistory: "Expense History",
      expenseHistoryDesc: "All recorded material & cost entries — sorted latest first",
      entries: "Entries:",
      totalSpent: "Total Spent:",
      productMaterial: "Product / Material",
      costPerUnit: "Cost / Unit",
      rank: "Rank",
      qtySold: "Qty Sold",
      revenue: "Revenue",
      deleteExpense: "Delete Expense",
      deleteExpenseConfirm: "This cannot be undone.",
    },
    stock: {
      title: "Stock Management",
      description: "Track inventory — recording an expense automatically updates stock",
      manualEntry: "Manual Stock Entry",
      linkedBanner: "Linked with Expenses: Every time you record a purchase in the Expenses tab, the stock quantity here is automatically increased. Use the",
      linkedBanner2: "button to reduce stock (sold, expired, broken, etc.).",
      totalItems: "Total Items",
      good: "Good",
      lowStock: "Low Stock",
      expiringSoon: "Expiring Soon",
      expiredOut: "Expired / Out",
      stockValue: "Stock Value",
      statusGood: "Good",
      statusLow: "Low Stock",
      statusOut: "Out of Stock",
      statusExpiringSoon: "Expiring Soon",
      statusExpired: "Expired",
      needAttention: "item(s) need attention",
      expiresIn: "Expires in",
      day: "day",
      days: "days",
      expiredReduceNow: "Expired — reduce stock now",
      outOfStock: "Out of stock",
      searchPlaceholder: "Search stock items...",
      allStatus: "All Status",
      stockInventory: "Stock Inventory",
      itemsShown: "items shown",
      noStockFound: "No stock items found",
      noStockDesc: "Add your first stock item to start tracking",
      addStockItem: "Add Stock Item",
      adjustmentHistory: "Adjustment History",
      records: "record(s) total",
      noAdjustments: "No adjustments recorded yet",
      colProduct: "Product / Material",
      colCategory: "Category",
      colQty: "Qty",
      colAvgCost: "Avg Cost/Unit",
      colStockValue: "Stock Value",
      colExpiry: "Expiry Date",
      colStatus: "Status",
      colActions: "Actions",
      colDateTime: "Date & Time",
      colType: "Type",
      colReason: "Reason",
      colQtyChanged: "Qty Changed",
      colBeforeAfter: "Before → After",
      colNotes: "Notes",
      typeAdded: "Added",
      typeReduced: "Reduced",
      reasonReceived: "Received",
      reasonSold: "Sold",
      reasonExpired: "Expired",
      reasonBroken: "Broken / Damaged",
      reasonReturned: "Returned to Supplier",
      reasonAdjustment: "Manual Adjustment",
      dLeft: "d left",
      dAgo: "d ago",
      expenseLinked: "Expense",
      addTitle: "Add New Stock Item",
      addDesc: "Manually add a product/material to your stock inventory",
      productName: "Product / Material Name *",
      productNamePH: "e.g. Brown Sugar, Tapioca Pearls...",
      category: "Category",
      categoryPH: "e.g. Ingredients",
      unitType: "Unit Type",
      initialQty: "Initial Stock Quantity *",
      expiryDate: "Expiry Date",
      optional: "optional",
      pricing: "Pricing (optional)",
      sellingPrice: "Selling Price (RM)",
      costPerUnit: "Cost Per Unit (RM)",
      notes: "Notes",
      notesPH: "Supplier, batch number, etc.",
      addToStock: "Add to Stock",
      topUpTitle: "Top Up Stock",
      topUpDesc: "Add more quantity to",
      current: "Current:",
      qtyToAdd: "Quantity to Add *",
      topUpNotesPH: "e.g. New delivery from supplier",
      afterTopUp: "After top-up:",
      topUp: "Top Up",
      reduceTitle: "Reduce Stock",
      reduceDesc: "Reduce quantity for",
      available: "Available:",
      reason: "Reason *",
      qtyToReduce: "Quantity to Reduce *",
      all: "All",
      afterReduction: "After reduction:",
      willEmpty: "⚠ This will empty the stock",
      deleteTitle: "Delete Stock Item",
      deleteDesc: "Remove from stock? This cannot be undone.",
    },
    settings: {
      title: "Settings",
      accountSettings: "Account Settings",
      subscriptionBilling: "Subscription & Billing",
      adminPanel: "Admin Panel",
      profileSettings: "Profile Settings",
      profileDesc: "Manage your account information",
      username: "Username",
      email: "Email",
      phoneNumber: "Phone Number",
      businessName: "Business Name",
      saveChanges: "Save Changes",
      dataManagement: "Data Management",
      dataManagementDesc: "Export or import your business data",
      exportData: "Export Data",
      importData: "Import Data",
      dataManagementHint: "Export as JSON for backup. Import to restore previous data.",
      security: "Security",
      securityDesc: "Manage your account security",
      password: "Password",
      passwordManagedBy: "Managed via Supabase Auth",
      changePassword: "Change Password",
      session: "Session",
      sessionDesc: "Manage your login session",
      currentSession: "Current Session",
      loggedInAs: "Logged in as",
      logout: "Logout",
      confirmLogout: "Confirm Logout",
      confirmLogoutDesc: "Are you sure you want to logout from AWC Trading?",
      language: "Language",
      languageDesc: "Choose your preferred display language",
    },
    units: {
      unit: "Unit",
      kg: "Kilogram (kg)",
      gram: "Gram (g)",
      liter: "Liter (L)",
      ml: "Milliliter (ml)",
      piece: "Piece",
    },
    billing: {
      statusActive: "Active",
      statusExpired: "Expired",
      statusGracePeriod: "Grace Period",
      statusCancelled: "Cancelled",
      statusTrial: "Free Trial",
      perMonth: "/month",
      daysRemaining: "days remaining · Renews",
      changePayment: "Change Payment",
      cancelSub: "Cancel subscription",
      subscribeNow: "Subscribe Now",
      autoDebitMandate: "Auto-Debit Mandate",
      autoDebitDesc: "Your authorized auto-debit via Curlec",
      fpxAutoDebit: "FPX Auto-Debit · Active",
      mandateId: "Mandate ID",
      autoDebitInfo: "RM59 will be automatically debited on the 1st of each month",
      whatsIncluded: "What's Included",
      billingHistory: "Billing History",
      billingHistoryDesc: "Your past subscription payments",
      securedBy: "Secured & Powered by",
      bnmLicensed: "BNM Licensed",
      paymentProcessedInfo: "All payments processed securely via Curlec (Razorpay Malaysia) · PayNet FPX · BNM Licensed",
      setupFpx: "Setup FPX Auto-Debit",
      setupFpxDesc: "Select your bank to proceed via FPX online banking",
      monthlyAutoDebit: "Monthly Auto-Debit via Curlec FPX",
      selectBank: "Select Your Bank",
      fpxRedirectInfo: "You will be redirected to your bank's secure online banking portal to complete payment",
      proceedTo: "Proceed to",
      paymentSuccess: "Payment Successful!",
      paymentSuccessDesc: "Your subscription has been activated via FPX",
      plan: "Plan",
      bank: "Bank",
      amountPaid: "Amount Paid",
      referenceNo: "Reference No",
      nextBilling: "Next Billing",
      receiptSent: "A receipt has been sent to your registered email. RM59 will be auto-debited monthly.",
      done: "Done",
      cancelSubTitle: "Cancel Subscription",
      cancelSubDesc: "Are you sure you want to cancel your AWC Business Plan?",
      willLoseAccess: "You will lose access to:",
      accessRemainsUntil: "Access remains active until",
      mandateCancelled: "The FPX mandate will be cancelled immediately.",
      keepSub: "Keep Subscription",
      yesCancel: "Yes, Cancel",
      features: [
        "Full POS Order Management",
        "Expense Tracking & Management",
        "Profit Analytics & Reports",
        "Product Image Management",
        "Receipt Printing",
        "Data Export & Import",
        "Cloud Sync (coming soon)",
        "Priority Support",
      ],
    },
  },

  ms: {
    nav: {
      orders: "Pesanan",
      expenses: "Perbelanjaan",
      analytics: "Analitik",
      settings: "Tetapan",
      stock: "Stok",
    },
    common: {
      save: "Simpan",
      cancel: "Batal",
      delete: "Padam",
      edit: "Edit",
      add: "Tambah",
      close: "Tutup",
      confirm: "Sahkan",
      total: "Jumlah",
      date: "Tarikh",
      notes: "Nota",
      export: "Eksport",
      import: "Import",
      loading: "Memuatkan...",
      saving: "Menyimpan...",
      saved: "Disimpan",
      offline: "Tiada Talian",
      cloudSync: "Segerak awan",
      signOut: "Log Keluar",
      actions: "Tindakan",
      quantity: "Kuantiti",
      unit: "Unit",
      or: "ATAU",
      remove: "Buang",
      businessSystem: "Sistem Pengurusan Perniagaan",
      renewNow: "Perbaharui Sekarang",
    },
    orders: {
      title: "Ringkasan Pesanan",
      cart: "Troli",
      items: "item",
      emptyCart: "Troli kosong",
      placeOrder: "Buat Pesanan",
      subtotal: "Jumlah Kecil",
      discount: "Diskaun",
      discountType: "Jenis Diskaun",
      percentage: "Peratusan (%)",
      fixedAmount: "Jumlah Tetap (RM)",
      discountPercentage: "Peratusan Diskaun",
      discountAmount: "Jumlah Diskaun",
      addToCart: "Tambah ke Troli",
      receipt: "Resit",
      printReceipt: "Cetak Resit",
      officialReceipt: "RESIT RASMI",
      receiptNo: "No. Resit",
      itemsLabel: "ITEM",
      thankYou: "Terima kasih atas sokongan anda!",
      comeAgain: "Sila datang lagi",
      pricePerUnit: "Harga:",
      totalLabel: "Jumlah:",
      subtotalLabel: "Jumlah Kecil:",
      totalFinal: "JUMLAH:",
      discountFixed: "(Tetap)",
      cashReceived: "Tunai Diterima",
      change: "Baki",
      payment: "Pembayaran",
      time: "Masa",
      paymentCash: "Tunai",
      paymentQr: "QR",
      paymentCard: "Kad",
    },
    expenses: {
      title: "Pengurusan Perbelanjaan",
      description: "Jejak kos dan bahan untuk produk anda",
      totalExpenses: "Jumlah Perbelanjaan",
      productManagement: "Pengurusan Produk",
      productManagementDesc: "Klik kad produk untuk log perbelanjaan. Gunakan togol untuk tunjuk atau sembunyikan produk dalam bahagian Pesanan.",
      recentExpenses: "Perbelanjaan Terkini",
      noExpenses: "Tiada perbelanjaan direkodkan",
      addExpense: "Tambah Perbelanjaan",
      addExpenseDesc: "Rekod kos bahan atau produk",
      addProduct: "Tambah Produk",
      addProductTitle: "Tambah Produk Baru",
      addProductDesc: "Cipta produk baru untuk jejak perbelanjaan",
      editProduct: "Edit Produk",
      editProductDesc: "Kemaskini butiran produk",
      deleteProduct: "Padam Produk",
      deleteProductConfirm: "Adakah anda pasti untuk memadam produk ini? Tindakan ini tidak boleh dibatalkan.",
      updateProduct: "Kemaskini Produk",
      productName: "Nama Produk",
      productNamePlaceholder: "cth: Boba Tea, Bijian Kopi",
      category: "Kategori",
      categoryPlaceholder: "cth: Minuman, Bahan",
      costPerUnit: "Kos per Unit (RM)",
      sellingPrice: "Harga Jualan (RM)",
      unitType: "Jenis Unit",
      initialStock: "Stok Awal",
      stock: "Stok",
      productImage: "Imej Produk",
      uploadImage: "Muat Naik Imej",
      pasteImageUrl: "Tampal URL imej di sini",
      showInOrders: "Papar dalam bahagian Pesanan",
      showInOrdersDesc: "Nyahcentang jika ini adalah bahan mentah yang tidak dijual secara langsung",
      inOrders: "✓ Dalam Pesanan",
      hidden: "✕ Tersembunyi",
      hideFromOrders: "Sembunyikan dari Pesanan",
      showInOrdersBtn: "Papar dalam Pesanan",
      totalCost: "Jumlah Kos",
      costPerUnitCol: "Kos/Unit",
      product: "Produk",
    },
    analytics: {
      title: "Analitik Keuntungan",
      totalRevenue: "Jumlah Hasil",
      totalCost: "Jumlah Kos",
      netProfit: "Keuntungan Bersih",
      profitMargin: "Margin Keuntungan",
      orders: "Pesanan",
      voidOrder: "Batalkan Pesanan",
      voidOrderConfirm: "Adakah anda pasti untuk membatalkan pesanan ini? Tindakan ini tidak boleh dibatalkan.",
      transactionHistory: "Sejarah Transaksi",
      transactionDesc: "Semua jualan selesai — terbaru dahulu",
      topProducts: "Produk Terlaris",
      topProductsDesc: "Produk terbaik mengikut hasil",
      salesReport: "Laporan Jualan",
      showingFor: "Papar ringkasan untuk:",
      todaySales: "Jualan Hari Ini",
      ordersToday: "pesanan hari ini",
      totalSales: "Jumlah Jualan",
      completedOrders: "pesanan selesai",
      totalExpenses: "Jumlah Perbelanjaan",
      expenseEntries: "entri perbelanjaan",
      margin: "margin",
      monthlyPerformance: "Prestasi Bulanan",
      monthlyDesc: "Pecahan jualan, perbelanjaan dan keuntungan",
      noTransactions: "Tiada transaksi untuk tempoh yang dipilih",
      noExpenses: "Tiada perbelanjaan untuk tempoh yang dipilih",
      noSalesData: "Tiada data jualan untuk tempoh yang dipilih",
      dateTime: "Tarikh & Masa",
      orderId: "ID Pesanan",
      items: "Item",
      amount: "Jumlah",
      showAll: "Papar Semua",
      showLess: "Papar Kurang",
      showing: "Menunjukkan",
      of: "daripada",
      expenseHistory: "Sejarah Perbelanjaan",
      expenseHistoryDesc: "Semua entri kos — terbaru dahulu",
      entries: "Entri:",
      totalSpent: "Jumlah Dibelanjakan:",
      productMaterial: "Produk / Bahan",
      costPerUnit: "Kos / Unit",
      rank: "Kedudukan",
      qtySold: "Qty Dijual",
      revenue: "Hasil",
      deleteExpense: "Padam Perbelanjaan",
      deleteExpenseConfirm: "Tindakan ini tidak boleh dibatalkan.",
    },
    stock: {
      title: "Pengurusan Stok",
      description: "Jejak inventori — merekod perbelanjaan secara automatik akan mengemaskini stok",
      manualEntry: "Entri Stok Manual",
      linkedBanner: "Dipautkan dengan Perbelanjaan: Setiap kali anda merekod pembelian dalam tab Perbelanjaan, kuantiti stok di sini akan ditambah secara automatik. Gunakan butang",
      linkedBanner2: "untuk kurangkan stok (dijual, tamat tempoh, rosak, dll.).",
      totalItems: "Jumlah Item",
      good: "Baik",
      lowStock: "Stok Rendah",
      expiringSoon: "Hampir Tamat Tempoh",
      expiredOut: "Tamat / Habis",
      stockValue: "Nilai Stok",
      statusGood: "Baik",
      statusLow: "Stok Rendah",
      statusOut: "Stok Habis",
      statusExpiringSoon: "Hampir Tamat Tempoh",
      statusExpired: "Tamat Tempoh",
      needAttention: "item memerlukan perhatian",
      expiresIn: "Tamat dalam",
      day: "hari",
      days: "hari",
      expiredReduceNow: "Tamat tempoh — kurangkan stok sekarang",
      outOfStock: "Stok habis",
      searchPlaceholder: "Cari item stok...",
      allStatus: "Semua Status",
      stockInventory: "Inventori Stok",
      itemsShown: "item ditunjukkan",
      noStockFound: "Tiada item stok ditemui",
      noStockDesc: "Tambah item stok pertama anda untuk mula menjejak",
      addStockItem: "Tambah Item Stok",
      adjustmentHistory: "Sejarah Pelarasan",
      records: "rekod keseluruhan",
      noAdjustments: "Tiada pelarasan direkodkan lagi",
      colProduct: "Produk / Bahan",
      colCategory: "Kategori",
      colQty: "Kuantiti",
      colAvgCost: "Kos Purata/Unit",
      colStockValue: "Nilai Stok",
      colExpiry: "Tarikh Luput",
      colStatus: "Status",
      colActions: "Tindakan",
      colDateTime: "Tarikh & Masa",
      colType: "Jenis",
      colReason: "Sebab",
      colQtyChanged: "Qty Berubah",
      colBeforeAfter: "Sebelum → Selepas",
      colNotes: "Nota",
      typeAdded: "Ditambah",
      typeReduced: "Dikurangkan",
      reasonReceived: "Diterima",
      reasonSold: "Dijual",
      reasonExpired: "Tamat Tempoh",
      reasonBroken: "Rosak / Pecah",
      reasonReturned: "Dipulangkan ke Pembekal",
      reasonAdjustment: "Pelarasan Manual",
      dLeft: "h lagi",
      dAgo: "h lalu",
      expenseLinked: "Perbelanjaan",
      addTitle: "Tambah Item Stok Baru",
      addDesc: "Tambah produk/bahan secara manual ke inventori stok anda",
      productName: "Nama Produk / Bahan *",
      productNamePH: "cth. Gula Perang, Mutiara Tapioka...",
      category: "Kategori",
      categoryPH: "cth. Bahan-bahan",
      unitType: "Jenis Unit",
      initialQty: "Kuantiti Stok Awal *",
      expiryDate: "Tarikh Luput",
      optional: "pilihan",
      pricing: "Harga (pilihan)",
      sellingPrice: "Harga Jualan (RM)",
      costPerUnit: "Kos Per Unit (RM)",
      notes: "Nota",
      notesPH: "Pembekal, nombor batch, dll.",
      addToStock: "Tambah ke Stok",
      topUpTitle: "Tambah Stok",
      topUpDesc: "Tambah kuantiti untuk",
      current: "Semasa:",
      qtyToAdd: "Kuantiti untuk Ditambah *",
      topUpNotesPH: "cth. Penghantaran baru dari pembekal",
      afterTopUp: "Selepas tambah:",
      topUp: "Tambah Stok",
      reduceTitle: "Kurangkan Stok",
      reduceDesc: "Kurangkan kuantiti untuk",
      available: "Tersedia:",
      reason: "Sebab *",
      qtyToReduce: "Kuantiti untuk Dikurangkan *",
      all: "Semua",
      afterReduction: "Selepas pengurangan:",
      willEmpty: "⚠ Ini akan mengosongkan stok",
      deleteTitle: "Padam Item Stok",
      deleteDesc: "Buang dari stok? Tindakan ini tidak boleh dibatalkan.",
    },
    settings: {
      title: "Tetapan",
      accountSettings: "Tetapan Akaun",
      subscriptionBilling: "Langganan & Bil",
      adminPanel: "Panel Admin",
      profileSettings: "Tetapan Profil",
      profileDesc: "Urus maklumat akaun anda",
      username: "Nama Pengguna",
      email: "E-mel",
      phoneNumber: "Nombor Telefon",
      businessName: "Nama Perniagaan",
      saveChanges: "Simpan Perubahan",
      dataManagement: "Pengurusan Data",
      dataManagementDesc: "Eksport atau import data perniagaan anda",
      exportData: "Eksport Data",
      importData: "Import Data",
      dataManagementHint: "Eksport sebagai JSON untuk sandaran. Import untuk memulihkan data sebelumnya.",
      security: "Keselamatan",
      securityDesc: "Urus keselamatan akaun anda",
      password: "Kata Laluan",
      passwordManagedBy: "Diurus melalui Supabase Auth",
      changePassword: "Tukar Kata Laluan",
      session: "Sesi",
      sessionDesc: "Urus sesi log masuk anda",
      currentSession: "Sesi Semasa",
      loggedInAs: "Log masuk sebagai",
      logout: "Log Keluar",
      confirmLogout: "Sahkan Log Keluar",
      confirmLogoutDesc: "Adakah anda pasti untuk log keluar dari AWC Trading?",
      language: "Bahasa",
      languageDesc: "Pilih bahasa paparan pilihan anda",
    },
    units: {
      unit: "Unit",
      kg: "Kilogram (kg)",
      gram: "Gram (g)",
      liter: "Liter (L)",
      ml: "Mililiter (ml)",
      piece: "Keping",
    },
    billing: {
      statusActive: "Aktif",
      statusExpired: "Tamat Tempoh",
      statusGracePeriod: "Tempoh Tangguh",
      statusCancelled: "Dibatalkan",
      statusTrial: "Percubaan Percuma",
      perMonth: "/bulan",
      daysRemaining: "hari lagi · Diperbaharui",
      changePayment: "Tukar Pembayaran",
      cancelSub: "Batalkan langganan",
      subscribeNow: "Langgan Sekarang",
      autoDebitMandate: "Mandat Debit Automatik",
      autoDebitDesc: "Debit automatik anda yang dibenarkan melalui Curlec",
      fpxAutoDebit: "Debit Auto FPX · Aktif",
      mandateId: "ID Mandat",
      autoDebitInfo: "RM59 akan didebit secara automatik pada 1hb setiap bulan",
      whatsIncluded: "Apa Yang Disertakan",
      billingHistory: "Sejarah Bil",
      billingHistoryDesc: "Pembayaran langganan anda yang lepas",
      securedBy: "Dijamin & Dikuasakan oleh",
      bnmLicensed: "Berlesen BNM",
      paymentProcessedInfo: "Semua pembayaran diproses dengan selamat melalui Curlec (Razorpay Malaysia) · PayNet FPX · Berlesen BNM",
      setupFpx: "Sedia Debit Auto FPX",
      setupFpxDesc: "Pilih bank anda untuk teruskan melalui perbankan dalam talian FPX",
      monthlyAutoDebit: "Debit Auto Bulanan via Curlec FPX",
      selectBank: "Pilih Bank Anda",
      fpxRedirectInfo: "Anda akan diarahkan ke portal perbankan dalam talian bank anda yang selamat untuk melengkapkan pembayaran",
      proceedTo: "Teruskan ke",
      paymentSuccess: "Pembayaran Berjaya!",
      paymentSuccessDesc: "Langganan anda telah diaktifkan melalui FPX",
      plan: "Pelan",
      bank: "Bank",
      amountPaid: "Jumlah Dibayar",
      referenceNo: "No. Rujukan",
      nextBilling: "Bil Seterusnya",
      receiptSent: "Resit telah dihantar ke e-mel berdaftar anda. RM59 akan didebit auto setiap bulan.",
      done: "Selesai",
      cancelSubTitle: "Batalkan Langganan",
      cancelSubDesc: "Adakah anda pasti untuk membatalkan Pelan Perniagaan AWC anda?",
      willLoseAccess: "Anda akan kehilangan akses kepada:",
      accessRemainsUntil: "Akses kekal aktif sehingga",
      mandateCancelled: "Mandat FPX akan dibatalkan serta-merta.",
      keepSub: "Kekalkan Langganan",
      yesCancel: "Ya, Batalkan",
      features: [
        "Pengurusan Pesanan POS Penuh",
        "Penjejakan & Pengurusan Perbelanjaan",
        "Analitik Keuntungan & Laporan",
        "Pengurusan Imej Produk",
        "Cetak Resit",
        "Eksport & Import Data",
        "Segerak Awan (akan datang)",
        "Sokongan Keutamaan",
      ],
    },
  },

  zh: {
    nav: {
      orders: "订单",
      expenses: "支出",
      analytics: "分析",
      settings: "设置",
      stock: "库存",
    },
    common: {
      save: "保存",
      cancel: "取消",
      delete: "删除",
      edit: "编辑",
      add: "添加",
      close: "关闭",
      confirm: "确认",
      total: "总计",
      date: "日期",
      notes: "备注",
      export: "导出",
      import: "导入",
      loading: "加载中...",
      saving: "保存中...",
      saved: "已保存",
      offline: "离线",
      cloudSync: "云同步",
      signOut: "退出登录",
      actions: "操作",
      quantity: "数量",
      unit: "单位",
      or: "或",
      remove: "移除",
      businessSystem: "企业管理系统",
      renewNow: "立即续费",
    },
    orders: {
      title: "订单摘要",
      cart: "购物车",
      items: "件",
      emptyCart: "购物车为空",
      placeOrder: "下订单",
      subtotal: "小计",
      discount: "折扣",
      discountType: "折扣类型",
      percentage: "百分比 (%)",
      fixedAmount: "固定金额 (RM)",
      discountPercentage: "折扣百分比",
      discountAmount: "折扣金额",
      addToCart: "加入购物车",
      receipt: "收据",
      printReceipt: "打印收据",
      officialReceipt: "正式收据",
      receiptNo: "收据编号",
      itemsLabel: "商品",
      thankYou: "感谢您的惠顾！",
      comeAgain: "欢迎再次光临",
      pricePerUnit: "价格：",
      totalLabel: "合计：",
      subtotalLabel: "小计：",
      totalFinal: "总计：",
      discountFixed: "（固定）",
      cashReceived: "收到现金",
      change: "找零",
      payment: "付款方式",
      time: "时间",
      paymentCash: "现金",
      paymentQr: "二维码",
      paymentCard: "刷卡",
    },
    expenses: {
      title: "支出管理",
      description: "跟踪产品的成本和材料",
      totalExpenses: "总支出",
      productManagement: "产品管理",
      productManagementDesc: "点击产品卡片记录支出。使用切换按钮在订单部分显示或隐藏产品。",
      recentExpenses: "近期支出",
      noExpenses: "暂无支出记录",
      addExpense: "添加支出",
      addExpenseDesc: "记录材料或产品的成本",
      addProduct: "添加产品",
      addProductTitle: "添加新产品",
      addProductDesc: "创建新产品以跟踪支出",
      editProduct: "编辑产品",
      editProductDesc: "更新产品详情",
      deleteProduct: "删除产品",
      deleteProductConfirm: "确定要删除此产品吗？此操作无法撤销。",
      updateProduct: "更新产品",
      productName: "产品名称",
      productNamePlaceholder: "例如：珍珠奶茶、咖啡豆",
      category: "类别",
      categoryPlaceholder: "例如：饮料、食材",
      costPerUnit: "单位成本 (RM)",
      sellingPrice: "销售价格 (RM)",
      unitType: "单位类型",
      initialStock: "初始库存",
      stock: "库存",
      productImage: "产品图片",
      uploadImage: "上传图片",
      pasteImageUrl: "粘贴图片链接",
      showInOrders: "在订单部分显示",
      showInOrdersDesc: "如果是原材料或不直接销售的食材，请关闭此选项",
      inOrders: "✓ 已在订单中",
      hidden: "✕ 已隐藏",
      hideFromOrders: "从订单隐藏",
      showInOrdersBtn: "在订单中显示",
      totalCost: "总成本",
      costPerUnitCol: "单位成本",
      product: "产品",
    },
    analytics: {
      title: "利润分析",
      totalRevenue: "总收入",
      totalCost: "总成本",
      netProfit: "净利润",
      profitMargin: "利润率",
      orders: "订单",
      voidOrder: "作废订单",
      voidOrderConfirm: "确定要作废此订单吗？此操作无法撤销。",
      transactionHistory: "交易记录",
      transactionDesc: "所有已完成销售 — 最新排前",
      topProducts: "热销产品",
      topProductsDesc: "按收入排列的最佳产品",
      salesReport: "销售报告",
      showingFor: "显示摘要：",
      todaySales: "今日销售",
      ordersToday: "今日订单",
      totalSales: "总销售额",
      completedOrders: "已完成订单",
      totalExpenses: "总支出",
      expenseEntries: "支出条目",
      margin: "利润率",
      monthlyPerformance: "月度表现",
      monthlyDesc: "销售、支出和利润细分",
      noTransactions: "所选时间段无交易记录",
      noExpenses: "所选时间段无支出记录",
      noSalesData: "所选时间段无销售数据",
      dateTime: "日期与时间",
      orderId: "订单编号",
      items: "商品",
      amount: "金额",
      showAll: "显示全部",
      showLess: "收起",
      showing: "显示",
      of: "共",
      expenseHistory: "支出历史",
      expenseHistoryDesc: "所有成本记录 — 最新排前",
      entries: "条目：",
      totalSpent: "总花费：",
      productMaterial: "产品 / 材料",
      costPerUnit: "单位成本",
      rank: "排名",
      qtySold: "销售数量",
      revenue: "收入",
      deleteExpense: "删除支出",
      deleteExpenseConfirm: "此操作无法撤销。",
    },
    stock: {
      title: "库存管理",
      description: "追踪库存 — 记录支出将自动更新库存",
      manualEntry: "手动添加库存",
      linkedBanner: "与支出关联：每次在支出标签页记录采购时，这里的库存数量会自动增加。使用",
      linkedBanner2: "按钮减少库存（已售、过期、损坏等）。",
      totalItems: "总项目",
      good: "良好",
      lowStock: "库存低",
      expiringSoon: "即将过期",
      expiredOut: "过期 / 缺货",
      stockValue: "库存价值",
      statusGood: "良好",
      statusLow: "库存低",
      statusOut: "缺货",
      statusExpiringSoon: "即将过期",
      statusExpired: "已过期",
      needAttention: "项目需要关注",
      expiresIn: "还有",
      day: "天",
      days: "天",
      expiredReduceNow: "已过期 — 请立即减少库存",
      outOfStock: "缺货",
      searchPlaceholder: "搜索库存项目...",
      allStatus: "所有状态",
      stockInventory: "库存清单",
      itemsShown: "项目已显示",
      noStockFound: "未找到库存项目",
      noStockDesc: "添加第一个库存项目开始追踪",
      addStockItem: "添加库存项目",
      adjustmentHistory: "调整历史",
      records: "条记录",
      noAdjustments: "暂无调整记录",
      colProduct: "产品 / 材料",
      colCategory: "类别",
      colQty: "数量",
      colAvgCost: "平均成本/单位",
      colStockValue: "库存价值",
      colExpiry: "到期日期",
      colStatus: "状态",
      colActions: "操作",
      colDateTime: "日期与时间",
      colType: "类型",
      colReason: "原因",
      colQtyChanged: "变更数量",
      colBeforeAfter: "前 → 后",
      colNotes: "备注",
      typeAdded: "已添加",
      typeReduced: "已减少",
      reasonReceived: "已收货",
      reasonSold: "已售出",
      reasonExpired: "已过期",
      reasonBroken: "损坏",
      reasonReturned: "退回供应商",
      reasonAdjustment: "手动调整",
      dLeft: "天后到期",
      dAgo: "天前",
      expenseLinked: "支出",
      addTitle: "添加新库存项目",
      addDesc: "手动将产品/材料添加到库存",
      productName: "产品 / 材料名称 *",
      productNamePH: "例如：红糖、木薯珍珠...",
      category: "类别",
      categoryPH: "例如：食材",
      unitType: "单位类型",
      initialQty: "初始库存数量 *",
      expiryDate: "到期日期",
      optional: "可选",
      pricing: "定价（可选）",
      sellingPrice: "销售价格 (RM)",
      costPerUnit: "每单位成本 (RM)",
      notes: "备注",
      notesPH: "供应商、批次号等",
      addToStock: "添加到库存",
      topUpTitle: "补充库存",
      topUpDesc: "添加更多数量到",
      current: "当前：",
      qtyToAdd: "添加数量 *",
      topUpNotesPH: "例如：供应商新到货",
      afterTopUp: "补充后：",
      topUp: "补充",
      reduceTitle: "减少库存",
      reduceDesc: "减少库存数量",
      available: "可用：",
      reason: "原因 *",
      qtyToReduce: "减少数量 *",
      all: "全部",
      afterReduction: "减少后：",
      willEmpty: "⚠ 这将清空库存",
      deleteTitle: "删除库存项目",
      deleteDesc: "从库存中移除？此操作无法撤销。",
    },
    settings: {
      title: "设置",
      accountSettings: "账户设置",
      subscriptionBilling: "订阅与账单",
      adminPanel: "管理员面板",
      profileSettings: "个人资料设置",
      profileDesc: "管理您的账户信息",
      username: "用户名",
      email: "电子邮件",
      phoneNumber: "电话号码",
      businessName: "企业名称",
      saveChanges: "保存更改",
      dataManagement: "数据管理",
      dataManagementDesc: "导出或导入您的业务数据",
      exportData: "导出数据",
      importData: "导入数据",
      dataManagementHint: "导出为JSON格式备份。导入以恢复之前的数据。",
      security: "安全",
      securityDesc: "管理您的账户安全",
      password: "密码",
      passwordManagedBy: "通过 Supabase Auth 管理",
      changePassword: "更改密码",
      session: "会话",
      sessionDesc: "管理您的登录会话",
      currentSession: "当前会话",
      loggedInAs: "已登录为",
      logout: "退出登录",
      confirmLogout: "确认退出",
      confirmLogoutDesc: "确定要退出 AWC Trading 吗？",
      language: "语言",
      languageDesc: "选择您偏好的显示语言",
    },
    units: {
      unit: "单位",
      kg: "千克 (kg)",
      gram: "克 (g)",
      liter: "升 (L)",
      ml: "毫升 (ml)",
      piece: "件",
    },
    billing: {
      statusActive: "已激活",
      statusExpired: "已过期",
      statusGracePeriod: "宽限期",
      statusCancelled: "已取消",
      statusTrial: "免费试用",
      perMonth: "/月",
      daysRemaining: "天后到期 · 续费日",
      changePayment: "更改付款方式",
      cancelSub: "取消订阅",
      subscribeNow: "立即订阅",
      autoDebitMandate: "自动扣款授权",
      autoDebitDesc: "您通过 Curlec 授权的自动扣款",
      fpxAutoDebit: "FPX 自动扣款 · 有效",
      mandateId: "授权编号",
      autoDebitInfo: "每月1日将自动扣除 RM59",
      whatsIncluded: "套餐包含",
      billingHistory: "账单历史",
      billingHistoryDesc: "您过去的订阅付款记录",
      securedBy: "安全保障 & 由以下提供",
      bnmLicensed: "BNM 持牌",
      paymentProcessedInfo: "所有付款通过 Curlec（Razorpay 马来西亚）· PayNet FPX · BNM 持牌安全处理",
      setupFpx: "设置 FPX 自动扣款",
      setupFpxDesc: "选择您的银行通过 FPX 网络银行继续",
      monthlyAutoDebit: "通过 Curlec FPX 每月自动扣款",
      selectBank: "选择您的银行",
      fpxRedirectInfo: "您将被重定向到银行的安全网络银行门户以完成付款",
      proceedTo: "前往",
      paymentSuccess: "付款成功！",
      paymentSuccessDesc: "您的订阅已通过 FPX 激活",
      plan: "套餐",
      bank: "银行",
      amountPaid: "已付金额",
      referenceNo: "参考编号",
      nextBilling: "下次账单",
      receiptSent: "收据已发送至您的注册邮箱。RM59 将每月自动扣除。",
      done: "完成",
      cancelSubTitle: "取消订阅",
      cancelSubDesc: "您确定要取消 AWC 商业套餐吗？",
      willLoseAccess: "您将失去以下访问权限：",
      accessRemainsUntil: "访问权限保持至",
      mandateCancelled: "FPX 授权将立即取消。",
      keepSub: "保留订阅",
      yesCancel: "是的，取消",
      features: [
        "完整 POS 订单管理",
        "支出跟踪与管理",
        "利润分析与报告",
        "产品图片管理",
        "打印收据",
        "数据导出与导入",
        "云同步（即将推出）",
        "优先支持",
      ],
    },
  },
};

export type T = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: T;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: translations.en,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const stored = localStorage.getItem("awc_language") as Language | null;
    return stored && ["en", "ms", "zh"].includes(stored) ? stored : "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("awc_language", lang);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t: translations[language] }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
